### ISSUE TITLE
Update to macOS 11 ?

### ISSUE THREAD

**Issue by johnwtt** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.6-Hackintosh#12]
Can you update the EFI so i can install macOS 11 ?

**Comment by whatnameisit** [comment]
What's the issue?

**Comment by johnwtt** [comment]
Boot loop happens: service exited due to sigabrt

**Comment by whatnameisit** [comment]
You know what. Google "install Big Sur OpenCore" and you'll see two adjustments you need to make to config.plist. Do it yourself.
I don't even know if you're going for Clover or OpenCore. I don't need to make out your minimum effort to describe the problem.
