### ISSUE TITLE
[BUG] Ultrawide videos visual glitches and flickering

### ISSUE THREAD

**Issue by florinsdistortedvision** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.6-Hackintosh#16]
**What is your laptop model? Does it fit the specs in [README](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.6-Hackintosh/blob/master/README.md#system-specification)?**
Model X510UA-BQ490

**Describe the bug**
While playing ultrawide Youtube videos, in fullscreen, various visual glitches and flickering appear.

**To Reproduce**
1. Go to https://youtu.be/PUrB5MvEPqQ
2. Select 1080p and fullscreen
3. Wait for the menu controls to disappear and wait a bit

**Expected behavior**
Video should play without problems.

**Additional context**
A fix that I found is rolling back the WhateverGreen kext from the latest one, to the 1.3.7 version which is odd, whenever updating it, the glitch happens again.

**Comment by whatnameisit** [comment]
I'm going to close this as well because you can never debug and describe the problem or the solution at all.
1.3.7 does not fix anything. File an issue at the Acidanthera bugtracker.
