### ISSUE TITLE
[BUG] 720p videos are actually 480p

### ISSUE THREAD

**Issue by florinsdistortedvision** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.6-Hackintosh#17]
**What is your laptop model? Does it fit the specs in [README](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.6-Hackintosh/blob/master/README.md#system-specification)?**
X510UA-BQ490

**Describe the bug**
 Selecting YouTube videos to 720p don't display the HD quality, rather they are 480p. You can see that the quality stays the same while selecting 720p and then back to 480p and back. No quality change.

**To Reproduce**
1. Go to any Youtube video
2. Click on 720p, wait for menu controls to disappear
3. Click on 480p, wait for menu controls to disappear
4. See error (no quality change)

**Expected behavior**
Video should be in HD while selecting 720p.

**Additional context**
1080p video displays fine.

**Comment by whatnameisit** [comment]
Proof that the actual resolution changes?
Make a report to YouTube.

**Comment by florinsdistortedvision** [comment]
Wow, thanks for the help bro! Wonder why you even post your files publicly when you only care about your build!

**Comment by whatnameisit** [comment]
You're being stupid. Does posting the build online not mean care for my build? The README says it's for my build and similar ones and use at your own risk. READ.
I actually tested it and the resolution indeed changes. PUT ON YOUR GLASSES
